import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :miata_bot, MiataBotWeb.Endpoint,
  url: [host: "miata-bot.sixtyeightplus.one", port: 80],
  server: true,
  cache_static_manifest: "priv/static/cache_manifest.json"

database_url =
  System.get_env("DATABASE_URL") ||
    raise """
    environment variable DATABASE_URL is missing.
    For example: ecto://USER:PASS@HOST/DATABASE
    """

config :miata_bot, MiataBot.Repo,
  # ssl: true,
  url: database_url,
  pool_size: 10

secret_key_base =
  System.get_env("SECRET_KEY_BASE") ||
    raise """
    environment variable SECRET_KEY_BASE is missing.
    You can generate one by calling: mix phx.gen.secret
    """

config :miata_bot, MiataBotWeb.Endpoint,
  server: true,
  http: [:inet6, port: String.to_integer(System.get_env("PORT") || "4000")],
  secret_key_base: secret_key_base

freenode_password =
  System.get_env("FREENODE_PASSWORD") ||
    raise """
    environment variable FREENODE_PASSWORD is missing.
    """

config :miata_bot, MiataBotIRC,
  host: "chat.freenode.net",
  port: 6667,
  nick: "MiataBot",
  user: "MiataBot",
  name: "MiataBot",
  pass: freenode_password
