import Config

config :tesla, adapter: Tesla.Adapter.Hackney

if System.get_env("RELEASE_MODE") do
  partpicker_api_token =
    System.get_env("PARTPICKER_API_TOKEN") ||
      raise """
      environment variable PARTPICKER_API_TOKEN is missing.
      This must be generated by the partpicker admins for production environment
      """

  config :miata_bot, MiataBot.Partpicker,
    api_token: partpicker_api_token,
    base_url: "https://partpicker.fly.dev/api"

  database_url =
    System.get_env("DATABASE_URL") ||
      raise """
      environment variable DATABASE_URL is missing.
      For example: ecto://USER:PASS@HOST/DATABASE
      """

  config :miata_bot, MiataBot.Repo,
    url: database_url,
    pool_size: 10,
    socket_options: [:inet6]

  quarrel_database_url =
    URI.parse(database_url)
    |> Map.put(:path, "/miata_bot_quarrel")
    |> to_string

  config :quarrel, Quarrel.Repo,
    url: quarrel_database_url,
    pool_size: 10,
    socket_options: [:inet6]

  config :nostrum,
    token: System.get_env("DISCORD_TOKEN"),
    gateway_intents: :all,
    num_shards: :auto
end
