name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName sixtyeightplus.one
            User www-data
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.sixtyeightplus.one
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.sixtyeightplus.one/miata_bot
          build-args: |
            SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
            DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}
            DISCORD_CLIENT_SECRET=${{ secrets.DISCORD_CLIENT_SECRET }}
            PARTPICKER_API_TOKEN=${{ secrets.PARTPICKER_API_TOKEN }}
            FREENODE_PASSWORD=${{ secrets.FREENODE_PASSWORD }}
      - name: Update instance
        run: |
          ssh deploy "docker-compose pull miata-bot; docker-compose up -d --no-deps miata-bot"

